name: Build

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  BASE_IMAGE_URI: "$IMAGE_REPO_URL/fantast03/jupyterlab"
  IMAGE_REPO_URL: "docker.io"


jobs:
  base-build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3 

    - name: "Login to docker registry"
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login $IMAGE_REPO_URL -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - name: "Build and push image into the repo"
      run: |
       IMAGE_TAG_NAME=base
       COMMIT_SHA=$(git rev-parse --short HEAD)
       FULL_IMAGE_NAME="$BASE_IMAGE_URI-$IMAGE_TAG_NAME"
       
       docker build . --file Dockerfile --no-cache -t $FULL_IMAGE_NAME:latest --target base
       docker push $FULL_IMAGE_NAME:latest

       docker tag $FULL_IMAGE_NAME:latest $FULL_IMAGE_NAME:$COMMIT_SHA
       docker push $FULL_IMAGE_NAME:$COMMIT_SHA
  
  machine-learning-build: 
    name: "Build machine learning notebook docker image"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3

    - name: "Login to docker registry"
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login $IMAGE_REPO_URL -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - name: "Build and push image into the repo"
      run: |
       IMAGE_TAG_NAME=machine-learning
       COMMIT_SHA=$(git rev-parse --short HEAD)
       FULL_IMAGE_NAME="$BASE_IMAGE_URI-$IMAGE_TAG"
       
       docker build . --file Dockerfile --no-cache -t $FULL_IMAGE_NAME:latest --target base
       docker push $FULL_IMAGE_NAME:latest

       docker tag $FULL_IMAGE_NAME:latest $FULL_IMAGE_NAME:$COMMIT_SHA
       docker push $FULL_IMAGE_NAME:$COMMIT_SHA