name: Build

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  IMAGE_REPO_URL: "docker.io"


jobs:
  base-build:

    runs-on: ubuntu-latest

    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3 

    - name: "Login to docker registry"
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login $IMAGE_REPO_URL -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - name: "Build and push image into the repo"
      run: |
       COMMIT_SHA=$(git rev-parse --short HEAD)
       FULL_IMAGE_URI="$IMAGE_REPO_URL/${{ secrets.DOCKER_LOGIN }}/jupyterlab-base"

       docker build . --file Dockerfile --no-cache -t $FULL_IMAGE_URI:latest --target base
       docker push $FULL_IMAGE_URI:latest

       docker tag $FULL_IMAGE_URI:latest $FULL_IMAGE_URI:$COMMIT_SHA
       docker push $FULL_IMAGE_URI:$COMMIT_SHA
  
  machine-learning-build: 
    name: "Build machine learning notebook docker image"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Check out the repo"
      uses: actions/checkout@v3

    - name: "Login to docker registry"
      run: echo "${{ secrets.DOCKER_PWD }}" | docker login $IMAGE_REPO_URL -u ${{ secrets.DOCKER_LOGIN }} --password-stdin

    - name: "Build and push image int o the repo"
      run: |
       COMMIT_SHA=$(git rev-parse --short HEAD)
       FULL_IMAGE_URI="$IMAGE_REPO_URL/${{ secrets.DOCKER_LOGIN }}/jupyterlab-machine-learning"
       
       docker build . --file Dockerfile --no-cache -t $FULL_IMAGE_URI:latest --target base
       docker push $FULL_IMAGE_URI:latest

       docker tag $FULL_IMAGE_URI:latest $FULL_IMAGE_URI:$COMMIT_SHA
       docker push $FULL_IMAGE_URI:$COMMIT_SHA